name = "QDScan"
uuid = "5c20f7fc-8785-4f79-944d-c9fa18151139"
authors = ["Chen Huang"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
